# Generated by Django 3.1 on 2022-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=30)),
                ('mobileNo', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=30)),
                ('Pincode', models.IntegerField()),
            ],
        ),
    ]
