# Generated by Django 3.1 on 2022-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0005_product_productdisplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='productimage1',
        ),
        migrations.AddField(
            model_name='product',
            name='productimage2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='productimage3',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
