# Generated by Django 3.1 on 2022-03-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0006_auto_20220302_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productprice', models.CharField(blank=True, max_length=10)),
                ('productdisc', models.CharField(blank=True, max_length=10)),
                ('productqty', models.CharField(blank=True, max_length=10)),
                ('productname', models.CharField(blank=True, max_length=20)),
                ('productimg', models.CharField(blank=True, max_length=100)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.product')),
            ],
        ),
    ]
