# Generated by Django 4.0.2 on 2022-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0009_alter_cart_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productqty',
            field=models.PositiveIntegerField(blank=True, max_length=10),
        ),
    ]
