# Generated by Django 3.1 on 2022-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0010_alter_cart_productqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productprice',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdisc',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productmrp',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
