# Generated by Django 4.0.2 on 2022-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0011_auto_20220304_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productprice',
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdisc',
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productmrp',
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.FloatField(blank=True, max_length=10),
        ),
    ]
