# Generated by Django 4.0.2 on 2022-03-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0013_alter_cart_productprice_alter_product_productdisc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productavaib',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
