# Generated by Django 4.0.2 on 2022-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0014_cart_productavaib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productprice',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productdisc',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productmrp',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productprice',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
