# Generated by Django 4.0.2 on 2022-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0020_alter_cart_productprice_alter_product_productdisc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Pincode',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='State',
            field=models.CharField(max_length=30),
        ),
    ]
