# Generated by Django 4.0.2 on 2022-03-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0022_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='fullname',
        ),
    ]
