# Generated by Django 4.0.2 on 2022-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0023_rename_name_contact_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
