# Generated by Django 4.0.2 on 2022-03-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0024_alter_contact_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
