# Generated by Django 4.0.2 on 2022-03-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0025_rename_fullname_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='City',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='State',
        ),
    ]
