# Generated by Django 4.0.2 on 2022-03-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0026_remove_registration_address_remove_registration_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(max_length=6)),
                ('C_Name', models.CharField(max_length=20)),
                ('C_mobileNo', models.CharField(max_length=30)),
                ('C_email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=30)),
                ('address2', models.TextField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('c_pincode', models.IntegerField(max_length=6)),
                ('amount', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=150)),
                ('productimg', models.CharField(blank=True, max_length=100)),
                ('p_price', models.IntegerField(blank=True, max_length=10)),
                ('p_qty', models.PositiveIntegerField(blank=True, max_length=10)),
                ('orderInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.myorder')),
            ],
        ),
    ]
