# Generated by Django 4.0.2 on 2022-03-31 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0028_alter_myorder_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='payment_mode',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Phone.product'),
            preserve_default=False,
        ),
    ]
