# Generated by Django 4.0.2 on 2022-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0029_myorder_payment_id_myorder_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='payment_mode',
            field=models.CharField(max_length=150),
        ),
    ]
