# Generated by Django 4.0.2 on 2022-03-31 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0030_alter_myorder_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.cart'),
        ),
    ]
