# Generated by Django 4.0.2 on 2022-03-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0031_alter_orderinfo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='product',
        ),
    ]
