# Generated by Django 4.0.2 on 2022-03-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0032_remove_orderinfo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Phone.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='p_name',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='p_price',
            field=models.IntegerField(blank=True, max_length=1000),
        ),
    ]
