# Generated by Django 4.0.2 on 2022-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0034_remove_orderinfo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for shopping', 'out for shopping'), ('completed', 'completed')], default='pending', max_length=150),
        ),
    ]
