# Generated by Django 4.0.2 on 2022-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0035_myorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(upload_to='banner')),
            ],
        ),
    ]
