# Generated by Django 4.0.2 on 2022-04-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0036_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner',
        ),
    ]
