# Generated by Django 4.0.2 on 2022-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0037_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
