# Generated by Django 4.0.2 on 2022-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0038_product_is_featured_product_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdisplay',
            field=models.FileField(blank=True, upload_to='product_display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productimage1',
            field=models.FileField(blank=True, upload_to='prod_img1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productimage2',
            field=models.FileField(blank=True, upload_to='prod_img2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productimage3',
            field=models.FileField(blank=True, upload_to='prod_img3'),
        ),
    ]
