# Generated by Django 4.0.2 on 2022-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0042_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestseller_display',
            field=models.FileField(blank=True, upload_to='bestseller_products'),
        ),
    ]
