# Generated by Django 4.0.2 on 2022-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0045_cart_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userId',
            field=models.CharField(max_length=30),
        ),
    ]
