# Generated by Django 4.0.2 on 2022-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0048_registration_address_registration_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Pincode',
            field=models.IntegerField(blank=True, max_length=6),
        ),
    ]
