# Generated by Django 4.0.2 on 2022-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0049_alter_registration_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='City',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='State',
        ),
    ]
