# Generated by Django 4.0.2 on 2022-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0050_remove_registration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=30)),
                ('mobileNo', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('State', models.CharField(blank=True, max_length=30)),
                ('City', models.CharField(blank=True, max_length=20)),
                ('Address', models.TextField(blank=True, max_length=30)),
                ('Address2', models.TextField(blank=True, max_length=30)),
                ('Pincode', models.IntegerField(blank=True, max_length=6)),
            ],
        ),
    ]
