# Generated by Django 4.0.2 on 2022-04-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0051_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
