# Generated by Django 4.0.2 on 2022-04-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0052_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productavaib',
        ),
    ]
