# Generated by Django 4.0.2 on 2022-04-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0053_remove_cart_productavaib'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
