# Generated by Django 4.0.2 on 2022-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0056_orderinfo_payment_id_orderinfo_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.IntegerField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
