# Generated by Django 4.0.2 on 2022-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0057_alter_contact_email_alter_contact_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='MobileNo',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
